# --- General options --- #
# bundle exec jekyll serve
# Name of website
title: Aryaman
tagline: I didn't exist

# Short description of your site
description: Click on the links to explore!

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this mean, then leave this section as it is. Only modify the url and baseurl if you know what you're doing!***

# url is the the website domain URL without a trailing slash
#url: "https://example.com"

# baseurl should be an empty string
#baseurl: ""

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  - title: Home
    href:  /
  - title: Academic
    subcategories:
    - title: Math
      href: /math/
    - title: Notes
      href:  /notes/
  - title: Tutorials
    href: /tuts/
    subcategories:
    - title: MA 105
      href:  /tuts/ma-105/
    - title: MA 106
      href:  /tuts/ma-106/
    - title: MA 108
      href:  /tuts/ma-108/
  - title: More
    subcategories:
    - title: Courses
      href:  /aboutme/courses/
    - title: Blog
      href:  /blog/
  - title: About Me
    href:  /aboutme/
  # Academic:
  #   - Notes: "notes/"
  #   - Reports: "reports/"
  #   - Presentations: "presentations/"
  # About Me: "aboutme/"
  # Tutorials:
  #   - MA 105: "tuts/ma-105/"
  #   - MA 106: "tuts/ma-106/"
  #   - MA 108: "tuts/ma-108/"
  # More:
  #   - Courses: "aboutme/courses/"
  #   - Blog: "blog/"
  #Dropdown:
  #  - Item 1: "http://www.google.com/"
  #  - Item 2: "http://www.github.com/"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

font-col: "#FFFFFF"
navbar-col: "#1B1B1B"
navbar-text-col: "#1C82B3"
navbar-children-col: "#181818"
page-col: "#373737"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#1B1B1B"
footer-text-col: "#FFFFFF"
footer-link-col: "#39688F"
title-col: "#D5D5D5"
subtitle-col: "#B4B4B4"

# light mode

light-font-col: "#000000"
light-navbar-col: "#E4E4E4"
light-navbar-text-col: "#E37D4C"
light-navbar-children-col: "#E7E7E7"
light-page-col: "#C8C8C8"
light-link-col: "#163DFF"
light-hover-col: "#FF7A5E"
light-footer-col: "#E4E4E4"
light-footer-text-col: "#000000"
light-footer-link-col: "#C69770"
light-title-col: "#2A2A2A"
light-subtitle-col: "#4B4B4B"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Aryaman Maithani

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "aryamanmaithani@gmail.com"
  # facebook: aryaman.maithani
  github: aryamanmaithani
  stackexchange: "427810/aryaman-maithani"
#  twitter: daattali
#  reddit: yourname
#  linkedin: aryaman-maithani
#  xing: yourname
#  snapchat: 
#  instagram: 
#  youtube: 
#  spotify: 
#  telephone: 
#  steam: 
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "aryamanmaithani.github.io"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "aryamanmaithani"

# If you want to use JustComments fill with the API Key
#just-comments: "ABCD-EFGH-IJKL"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# Staticman support
staticman:
  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance)
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
#timezone: Asia/Calcutta
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

paginate_path: "/blog/page:num/"
collections:
  reports: 
    output: true
  presentations: 
    output: true

anon-form: "https://forms.gle/faFYkmjNnevF5nBK9"
plugins:
  - jekyll-target-blank